export const singleProductData = {
  product_id: 130,
  name: "new product test 00 (10-05-2023)",
  slug: "new-product-test-00-10-05-2023",
  main_picture:
    "https://amarpet-space.sgp1.digitaloceanspaces.com/development/5ef698cd9fe650923ea331c15af3b160/lDFAPHrp0C5TWnraa8ACa6bw2FuZeA-metaaWFtcyAyLmpwZWc=-.jpg",
  pictures: [
    {
      path: "https://amarpet-space.sgp1.digitaloceanspaces.com/development/5ef698cd9fe650923ea331c15af3b160/lDFAPHrp0C5TWnraa8ACa6bw2FuZeA-metaaWFtcyAyLmpwZWc=-.jpg",
    },
  ],
  attributes: [
    {
      name: "new attribute test 00 (10-05-2023)",
      values: [
        {
          value: "test 1",
        },
        {
          value: "test 2",
        },
        {
          value: "test 3",
        },
      ],
    },
    {
      name: "Carrier",
      values: [
        {
          value: "Airtel number",
        },
        {
          value: "Banglalink number",
        },
        {
          value: "Grameenphone number",
        },
      ],
    },
    {
      name: "Color",
      values: [
        {
          value: "Blackk",
        },
        {
          value: "Purplee",
        },
        {
          value: "Redd",
        },
        {
          value: "Whitee",
        },
        {
          value: "Yelloww",
        },
      ],
    },
  ],
  variations: [
    {
      name: "Carrier: Airtel number | Color: Blackk | new attribute test 00 (10-05-2023): test 1",
      sku: null,
      variation: "EWCDJKHFWW",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 1",
        },
        {
          name: "Carrier",
          value: "Airtel number",
        },
        {
          name: "Color",
          value: "Blackk",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Grameenphone number | Color: Purplee | new attribute test 00 (10-05-2023): test 2",
      sku: null,
      variation: "YZXYMUWVVO",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 2",
        },
        {
          name: "Carrier",
          value: "Grameenphone number",
        },
        {
          name: "Color",
          value: "Purplee",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Airtel number | Color: Yelloww | new attribute test 00 (10-05-2023): test 3",
      sku: null,
      variation: "02721b9f-11b6-4af0-8ca5-e4a9832c7b1d",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 3",
        },
        {
          name: "Carrier",
          value: "Airtel number",
        },
        {
          name: "Color",
          value: "Yelloww",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Airtel number | Color: Whitee | new attribute test 00 (10-05-2023): test 3",
      sku: null,
      variation: "338132fc-a6f9-4c71-ac9e-701e0147bb33",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 3",
        },
        {
          name: "Carrier",
          value: "Airtel number",
        },
        {
          name: "Color",
          value: "Whitee",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Airtel number | Color: Redd | new attribute test 00 (10-05-2023): test 3",
      sku: null,
      variation: "35ee6770-6064-457a-bcea-4086ae37bb37",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 3",
        },
        {
          name: "Carrier",
          value: "Airtel number",
        },
        {
          name: "Color",
          value: "Redd",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Airtel number | Color: Purplee | new attribute test 00 (10-05-2023): test 3",
      sku: null,
      variation: "e2cacad3-acc3-4781-804a-b08bddab49a4",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 3",
        },
        {
          name: "Carrier",
          value: "Airtel number",
        },
        {
          name: "Color",
          value: "Purplee",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Airtel number | Color: Blackk | new attribute test 00 (10-05-2023): test 3",
      sku: null,
      variation: "5a68fbcd-69e4-49ae-b766-ab3f9498d96a",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 3",
        },
        {
          name: "Carrier",
          value: "Airtel number",
        },
        {
          name: "Color",
          value: "Blackk",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Grameenphone number | Color: Yelloww | new attribute test 00 (10-05-2023): test 2",
      sku: null,
      variation: "ALDBICZMSJ",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 2",
        },
        {
          name: "Carrier",
          value: "Grameenphone number",
        },
        {
          name: "Color",
          value: "Yelloww",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Grameenphone number | Color: Whitee | new attribute test 00 (10-05-2023): test 2",
      sku: null,
      variation: "DCSHTEJQRC",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 2",
        },
        {
          name: "Carrier",
          value: "Grameenphone number",
        },
        {
          name: "Color",
          value: "Whitee",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Grameenphone number | Color: Redd | new attribute test 00 (10-05-2023): test 2",
      sku: null,
      variation: "FKRXTXZQIX",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 2",
        },
        {
          name: "Carrier",
          value: "Grameenphone number",
        },
        {
          name: "Color",
          value: "Redd",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Banglalink number | Color: Redd | new attribute test 00 (10-05-2023): test 3",
      sku: null,
      variation: "3c32b331-5bb8-43d1-8810-e931ca6dfc48",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 3",
        },
        {
          name: "Carrier",
          value: "Banglalink number",
        },
        {
          name: "Color",
          value: "Redd",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Grameenphone number | Color: Blackk | new attribute test 00 (10-05-2023): test 2",
      sku: null,
      variation: "HZCYRVPHYO",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 2",
        },
        {
          name: "Carrier",
          value: "Grameenphone number",
        },
        {
          name: "Color",
          value: "Blackk",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Banglalink number | Color: Yelloww | new attribute test 00 (10-05-2023): test 2",
      sku: null,
      variation: "BZYCNUMYBE",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 2",
        },
        {
          name: "Carrier",
          value: "Banglalink number",
        },
        {
          name: "Color",
          value: "Yelloww",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Banglalink number | Color: Whitee | new attribute test 00 (10-05-2023): test 2",
      sku: null,
      variation: "TMFRSFWKPN",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 2",
        },
        {
          name: "Carrier",
          value: "Banglalink number",
        },
        {
          name: "Color",
          value: "Whitee",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Banglalink number | Color: Blackk | new attribute test 00 (10-05-2023): test 3",
      sku: null,
      variation: "bcab437c-0df5-4634-bbe4-8bc16d23f815",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 3",
        },
        {
          name: "Carrier",
          value: "Banglalink number",
        },
        {
          name: "Color",
          value: "Blackk",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Banglalink number | Color: Purplee | new attribute test 00 (10-05-2023): test 3",
      sku: null,
      variation: "8846423a-ab68-46bd-a9b0-cec21a43dcc0",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 3",
        },
        {
          name: "Carrier",
          value: "Banglalink number",
        },
        {
          name: "Color",
          value: "Purplee",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Banglalink number | Color: Purplee | new attribute test 00 (10-05-2023): test 2",
      sku: null,
      variation: "STNFGKOWDX",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 2",
        },
        {
          name: "Carrier",
          value: "Banglalink number",
        },
        {
          name: "Color",
          value: "Purplee",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Banglalink number | Color: Whitee | new attribute test 00 (10-05-2023): test 3",
      sku: null,
      variation: "2aa82b33-6f16-43f3-bda3-cef478472768",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 3",
        },
        {
          name: "Carrier",
          value: "Banglalink number",
        },
        {
          name: "Color",
          value: "Whitee",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Banglalink number | Color: Yelloww | new attribute test 00 (10-05-2023): test 3",
      sku: null,
      variation: "b3c29551-5f28-48e8-a263-04c5c7cbf002",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 3",
        },
        {
          name: "Carrier",
          value: "Banglalink number",
        },
        {
          name: "Color",
          value: "Yelloww",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Grameenphone number | Color: Blackk | new attribute test 00 (10-05-2023): test 3",
      sku: null,
      variation: "20cbbb3e-e117-4a05-af69-9a44b6d57159",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 3",
        },
        {
          name: "Carrier",
          value: "Grameenphone number",
        },
        {
          name: "Color",
          value: "Blackk",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Grameenphone number | Color: Purplee | new attribute test 00 (10-05-2023): test 3",
      sku: null,
      variation: "d6e90621-9dae-4dbd-8fab-ebbfcc95c999",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 3",
        },
        {
          name: "Carrier",
          value: "Grameenphone number",
        },
        {
          name: "Color",
          value: "Purplee",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Grameenphone number | Color: Redd | new attribute test 00 (10-05-2023): test 3",
      sku: null,
      variation: "1a265a68-f3b0-448e-ae61-cc6c55df4438",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 3",
        },
        {
          name: "Carrier",
          value: "Grameenphone number",
        },
        {
          name: "Color",
          value: "Redd",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Grameenphone number | Color: Whitee | new attribute test 00 (10-05-2023): test 3",
      sku: null,
      variation: "bc33564a-36f5-4f3f-94eb-28ffe082defe",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 3",
        },
        {
          name: "Carrier",
          value: "Grameenphone number",
        },
        {
          name: "Color",
          value: "Whitee",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Grameenphone number | Color: Yelloww | new attribute test 00 (10-05-2023): test 3",
      sku: null,
      variation: "2da1489f-77f2-4d05-bc9d-741b824df421",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 3",
        },
        {
          name: "Carrier",
          value: "Grameenphone number",
        },
        {
          name: "Color",
          value: "Yelloww",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Banglalink number | Color: Whitee | new attribute test 00 (10-05-2023): test 1",
      sku: null,
      variation: "JGGSMZBTFL",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 1",
        },
        {
          name: "Carrier",
          value: "Banglalink number",
        },
        {
          name: "Color",
          value: "Whitee",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Airtel number | Color: Purplee | new attribute test 00 (10-05-2023): test 1",
      sku: null,
      variation: "VYFMAEZEHT",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 1",
        },
        {
          name: "Carrier",
          value: "Airtel number",
        },
        {
          name: "Color",
          value: "Purplee",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Airtel number | Color: Redd | new attribute test 00 (10-05-2023): test 1",
      sku: null,
      variation: "MEEORGKBHS",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 1",
        },
        {
          name: "Carrier",
          value: "Airtel number",
        },
        {
          name: "Color",
          value: "Redd",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Airtel number | Color: Whitee | new attribute test 00 (10-05-2023): test 1",
      sku: null,
      variation: "TTMRPTGXYW",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 1",
        },
        {
          name: "Carrier",
          value: "Airtel number",
        },
        {
          name: "Color",
          value: "Whitee",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Airtel number | Color: Yelloww | new attribute test 00 (10-05-2023): test 1",
      sku: null,
      variation: "AIUHCDZYPY",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 1",
        },
        {
          name: "Carrier",
          value: "Airtel number",
        },
        {
          name: "Color",
          value: "Yelloww",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Banglalink number | Color: Blackk | new attribute test 00 (10-05-2023): test 1",
      sku: null,
      variation: "IFZCKLIJIS",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 1",
        },
        {
          name: "Carrier",
          value: "Banglalink number",
        },
        {
          name: "Color",
          value: "Blackk",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Banglalink number | Color: Purplee | new attribute test 00 (10-05-2023): test 1",
      sku: null,
      variation: "OIHCVMJQEL",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 1",
        },
        {
          name: "Carrier",
          value: "Banglalink number",
        },
        {
          name: "Color",
          value: "Purplee",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Banglalink number | Color: Redd | new attribute test 00 (10-05-2023): test 1",
      sku: null,
      variation: "EILENMXCGL",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 1",
        },
        {
          name: "Carrier",
          value: "Banglalink number",
        },
        {
          name: "Color",
          value: "Redd",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Banglalink number | Color: Redd | new attribute test 00 (10-05-2023): test 2",
      sku: null,
      variation: "DAREQUDONL",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 2",
        },
        {
          name: "Carrier",
          value: "Banglalink number",
        },
        {
          name: "Color",
          value: "Redd",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Banglalink number | Color: Yelloww | new attribute test 00 (10-05-2023): test 1",
      sku: null,
      variation: "CIDUKMECGS",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 1",
        },
        {
          name: "Carrier",
          value: "Banglalink number",
        },
        {
          name: "Color",
          value: "Yelloww",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Grameenphone number | Color: Blackk | new attribute test 00 (10-05-2023): test 1",
      sku: null,
      variation: "JIHHITGCRQ",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 1",
        },
        {
          name: "Carrier",
          value: "Grameenphone number",
        },
        {
          name: "Color",
          value: "Blackk",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Grameenphone number | Color: Purplee | new attribute test 00 (10-05-2023): test 1",
      sku: null,
      variation: "KGACDELUUR",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 1",
        },
        {
          name: "Carrier",
          value: "Grameenphone number",
        },
        {
          name: "Color",
          value: "Purplee",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Grameenphone number | Color: Redd | new attribute test 00 (10-05-2023): test 1",
      sku: null,
      variation: "WMMBQQCTDK",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 1",
        },
        {
          name: "Carrier",
          value: "Grameenphone number",
        },
        {
          name: "Color",
          value: "Redd",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Grameenphone number | Color: Whitee | new attribute test 00 (10-05-2023): test 1",
      sku: null,
      variation: "JRESELYVXN",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 1",
        },
        {
          name: "Carrier",
          value: "Grameenphone number",
        },
        {
          name: "Color",
          value: "Whitee",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Grameenphone number | Color: Yelloww | new attribute test 00 (10-05-2023): test 1",
      sku: null,
      variation: "UNAAKJWSKO",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 1",
        },
        {
          name: "Carrier",
          value: "Grameenphone number",
        },
        {
          name: "Color",
          value: "Yelloww",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Airtel number | Color: Blackk | new attribute test 00 (10-05-2023): test 2",
      sku: null,
      variation: "YYFJQZVWHX",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 2",
        },
        {
          name: "Carrier",
          value: "Airtel number",
        },
        {
          name: "Color",
          value: "Blackk",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Airtel number | Color: Purplee | new attribute test 00 (10-05-2023): test 2",
      sku: null,
      variation: "ACIDTNCPBQ",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 2",
        },
        {
          name: "Carrier",
          value: "Airtel number",
        },
        {
          name: "Color",
          value: "Purplee",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Airtel number | Color: Redd | new attribute test 00 (10-05-2023): test 2",
      sku: null,
      variation: "EXQNNTMQGV",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 2",
        },
        {
          name: "Carrier",
          value: "Airtel number",
        },
        {
          name: "Color",
          value: "Redd",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Airtel number | Color: Whitee | new attribute test 00 (10-05-2023): test 2",
      sku: null,
      variation: "RRTWHGDXJL",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 2",
        },
        {
          name: "Carrier",
          value: "Airtel number",
        },
        {
          name: "Color",
          value: "Whitee",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Airtel number | Color: Yelloww | new attribute test 00 (10-05-2023): test 2",
      sku: null,
      variation: "NVSSCONOVU",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 2",
        },
        {
          name: "Carrier",
          value: "Airtel number",
        },
        {
          name: "Color",
          value: "Yelloww",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
    {
      name: "Carrier: Banglalink number | Color: Blackk | new attribute test 00 (10-05-2023): test 2",
      sku: null,
      variation: "EZVJHHWHZF",
      pictures: [],
      price: 2200,
      discount_amount: 0,
      offer_percent: 0,
      offer_price: 0,
      offer_start_date: null,
      offer_end_date: null,
      unit_quantity: 1,
      inventory: 0,
      values: [
        {
          name: "new attribute test 00 (10-05-2023)",
          value: "test 2",
        },
        {
          name: "Carrier",
          value: "Banglalink number",
        },
        {
          name: "Color",
          value: "Blackk",
        },
      ],
      in_cart: false,
      in_cart_quantity: 0,
      in_wishList: false,
    },
  ],
  variation_names: [
    {
      Carrier: "Airtel number",
      Color: "Blackk",
      "new attribute test 00 (10-05-2023)": "test 1",
    },
    {
      Carrier: "Grameenphone number",
      Color: "Purplee",
      "new attribute test 00 (10-05-2023)": "test 2",
    },
    {
      Carrier: "Airtel number",
      Color: "Yelloww",
      "new attribute test 00 (10-05-2023)": "test 3",
    },
    {
      Carrier: "Airtel number",
      Color: "Whitee",
      "new attribute test 00 (10-05-2023)": "test 3",
    },
    {
      Carrier: "Airtel number",
      Color: "Redd",
      "new attribute test 00 (10-05-2023)": "test 3",
    },
    {
      Carrier: "Airtel number",
      Color: "Purplee",
      "new attribute test 00 (10-05-2023)": "test 3",
    },
    {
      Carrier: "Airtel number",
      Color: "Blackk",
      "new attribute test 00 (10-05-2023)": "test 3",
    },
    {
      Carrier: "Grameenphone number",
      Color: "Yelloww",
      "new attribute test 00 (10-05-2023)": "test 2",
    },
    {
      Carrier: "Grameenphone number",
      Color: "Whitee",
      "new attribute test 00 (10-05-2023)": "test 2",
    },
    {
      Carrier: "Grameenphone number",
      Color: "Redd",
      "new attribute test 00 (10-05-2023)": "test 2",
    },
    {
      Carrier: "Banglalink number",
      Color: "Redd",
      "new attribute test 00 (10-05-2023)": "test 3",
    },
    {
      Carrier: "Grameenphone number",
      Color: "Blackk",
      "new attribute test 00 (10-05-2023)": "test 2",
    },
    {
      Carrier: "Banglalink number",
      Color: "Yelloww",
      "new attribute test 00 (10-05-2023)": "test 2",
    },
    {
      Carrier: "Banglalink number",
      Color: "Whitee",
      "new attribute test 00 (10-05-2023)": "test 2",
    },
    {
      Carrier: "Banglalink number",
      Color: "Blackk",
      "new attribute test 00 (10-05-2023)": "test 3",
    },
    {
      Carrier: "Banglalink number",
      Color: "Purplee",
      "new attribute test 00 (10-05-2023)": "test 3",
    },
    {
      Carrier: "Banglalink number",
      Color: "Purplee",
      "new attribute test 00 (10-05-2023)": "test 2",
    },
    {
      Carrier: "Banglalink number",
      Color: "Whitee",
      "new attribute test 00 (10-05-2023)": "test 3",
    },
    {
      Carrier: "Banglalink number",
      Color: "Yelloww",
      "new attribute test 00 (10-05-2023)": "test 3",
    },
    {
      Carrier: "Grameenphone number",
      Color: "Blackk",
      "new attribute test 00 (10-05-2023)": "test 3",
    },
    {
      Carrier: "Grameenphone number",
      Color: "Purplee",
      "new attribute test 00 (10-05-2023)": "test 3",
    },
    {
      Carrier: "Grameenphone number",
      Color: "Redd",
      "new attribute test 00 (10-05-2023)": "test 3",
    },
    {
      Carrier: "Grameenphone number",
      Color: "Whitee",
      "new attribute test 00 (10-05-2023)": "test 3",
    },
    {
      Carrier: "Grameenphone number",
      Color: "Yelloww",
      "new attribute test 00 (10-05-2023)": "test 3",
    },
    {
      Carrier: "Banglalink number",
      Color: "Whitee",
      "new attribute test 00 (10-05-2023)": "test 1",
    },
    {
      Carrier: "Airtel number",
      Color: "Purplee",
      "new attribute test 00 (10-05-2023)": "test 1",
    },
    {
      Carrier: "Airtel number",
      Color: "Redd",
      "new attribute test 00 (10-05-2023)": "test 1",
    },
    {
      Carrier: "Airtel number",
      Color: "Whitee",
      "new attribute test 00 (10-05-2023)": "test 1",
    },
    {
      Carrier: "Airtel number",
      Color: "Yelloww",
      "new attribute test 00 (10-05-2023)": "test 1",
    },
    {
      Carrier: "Banglalink number",
      Color: "Blackk",
      "new attribute test 00 (10-05-2023)": "test 1",
    },
    {
      Carrier: "Banglalink number",
      Color: "Purplee",
      "new attribute test 00 (10-05-2023)": "test 1",
    },
    {
      Carrier: "Banglalink number",
      Color: "Redd",
      "new attribute test 00 (10-05-2023)": "test 1",
    },
    {
      Carrier: "Banglalink number",
      Color: "Redd",
      "new attribute test 00 (10-05-2023)": "test 2",
    },
    {
      Carrier: "Banglalink number",
      Color: "Yelloww",
      "new attribute test 00 (10-05-2023)": "test 1",
    },
    {
      Carrier: "Grameenphone number",
      Color: "Blackk",
      "new attribute test 00 (10-05-2023)": "test 1",
    },
    {
      Carrier: "Grameenphone number",
      Color: "Purplee",
      "new attribute test 00 (10-05-2023)": "test 1",
    },
    {
      Carrier: "Grameenphone number",
      Color: "Redd",
      "new attribute test 00 (10-05-2023)": "test 1",
    },
    {
      Carrier: "Grameenphone number",
      Color: "Whitee",
      "new attribute test 00 (10-05-2023)": "test 1",
    },
    {
      Carrier: "Grameenphone number",
      Color: "Yelloww",
      "new attribute test 00 (10-05-2023)": "test 1",
    },
    {
      Carrier: "Airtel number",
      Color: "Blackk",
      "new attribute test 00 (10-05-2023)": "test 2",
    },
    {
      Carrier: "Airtel number",
      Color: "Purplee",
      "new attribute test 00 (10-05-2023)": "test 2",
    },
    {
      Carrier: "Airtel number",
      Color: "Redd",
      "new attribute test 00 (10-05-2023)": "test 2",
    },
    {
      Carrier: "Airtel number",
      Color: "Whitee",
      "new attribute test 00 (10-05-2023)": "test 2",
    },
    {
      Carrier: "Airtel number",
      Color: "Yelloww",
      "new attribute test 00 (10-05-2023)": "test 2",
    },
    {
      Carrier: "Banglalink number",
      Color: "Blackk",
      "new attribute test 00 (10-05-2023)": "test 2",
    },
  ],
  brand: {
    name: "new brand test 00 (10-05-2023)",
    slug: "new-brand-test-00-10-05-2023",
    description: null,
    link: "new-brand-test-00-10-05-2023",
    banner:
      "https://amarpet-space.sgp1.digitaloceanspaces.com/development/c3e878e27f52e2a57ace4d9a76fd9acf/7fSwKQbjTR9qNbrtQl2NVsQtiIruVj-metaTE9HTy5qcGVn-.jpg",
    logo: "https://amarpet-space.sgp1.digitaloceanspaces.com/development/c3e878e27f52e2a57ace4d9a76fd9acf/7fSwKQbjTR9qNbrtQl2NVsQtiIruVj-metaTE9HTy5qcGVn-.jpg",
  },
  categories: [
    {
      name: "cat litter check",
      slug: "cat-litter-check",
      description: null,
      logo: "https://dev-admin.amarpet.com/images/category/logo.webp",
      banner: "https://dev-admin.amarpet.com/images/category/banner.png",
      full_path: "cat litter check^cat-litter-check",
    },
  ],
  sku: null,
  price: 2200,
  discount_amount: 0,
  offer_percent: 0,
  offer_price: 0,
  offer_start_date: null,
  offer_end_date: null,
  is_variation: 1,
  status: 1,
  desc: "Description",
  inventory: 0,
  in_cart: false,
  in_cart_quantity: 0,
  in_wishList: false,
  default_variation: {
    name: "new attribute test 00 (10-05-2023): test 1, Carrier: Airtel number, Color: Blackk",
    sku: null,
    variation: "EWCDJKHFWW",
    pictures: [],
    price: 2200,
    discount_amount: 0,
    offer_percent: 0,
    offer_price: 0,
    offer_start_date: null,
    offer_end_date: null,
    unit_quantity: 1,
    inventory: 0,
    values: [
      {
        name: "new attribute test 00 (10-05-2023)",
        value: "test 1",
      },
      {
        name: "Carrier",
        value: "Airtel number",
      },
      {
        name: "Color",
        value: "Blackk",
      },
    ],
    in_cart: false,
    in_cart_quantity: 0,
    in_wishList: false,
  },
};

export const singleProductGetData = {
  200: {
    message: "Success",
    errors: [],
    data: {
      product: singleProductData,
      related_products: [
        {
          ...singleProductData,
        },
      ],
      metadata: {
        title: "Product Name",
        description: "Product Description",
        keywords: "Product Keywords",
        url: "http://localhost:8000/product/banana",
        keimageywords: "http://localhost:8000/product.webp",
      },
    },
  },
};

export const allProductGetData = {
  200: {
    data: [{ ...singleProductData }, { ...singleProductData }],
    meta: {
      current_page: 1,
      from: 1,
      last_page: 1,
      path: "http://localhost/api/v1/products",
      per_page: 15,
      to: 1,
      total: 1,
    },
    links: {
      first: "http://localhost/api/v1/products?page=1",
      last: "http://localhost/api/v1/products?page=1",
      prev: "http://localhost/api/v1/products?page=1",
      next: "http://localhost/api/v1/products?page=1",
    },
  },
};
