name: "Deploy nextjs application on development server"

on:
  push:
    branches:
      - v1.x

jobs:
  development-build-deploy:
    name: Development server build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.18.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.0
      - run: npm i -g npm@8.5.0
      - run: node -v
      - run: npm -v
      - run: export NVM_DIR=~/.nvm
      - run: source ~/.nvm/nvm.sh
      - run: cp .env.example .env.local
      - run: cp .env.example .env
      - run: npm install
      - run: npm run build

      - name: Build file copy to dev server
        if: ${{ success() }}
        env:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
        run: |
          mkdir -p ~/.ssh
          echo "$key" >> ~/.ssh/id_rsa_amarpet
          chmod 600 ~/.ssh/id_rsa_amarpet
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa_amarpet
          ssh-keyscan -H $host >> ~/.ssh/known_hosts
          ssh $username@$host "cd /var/www/customer-panel/; rm -r .next;"
          scp -r .next $username@$host:/var/www/customer-panel/.next/

      - name: Executing remote ssh commands using password
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/customer-panel
            git pull origin v1.x
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            pm2 restart amarpet-dev amarpet-dev-storybook

      - name: Develop Build Status
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://amrpet.com/favicon.png
          SLACK_MESSAGE: Develop Build Failed
          SLACK_TITLE: AmarPet Frontend Develop Build Status
          SLACK_USERNAME: AmarPet Frontend Dev Server
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
